---
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8011/eureka/,http://localhost:8012/eureka/,http://localhost:8013/eureka/
--
spring:
  profiles: subject
words: I,You,He,She,It
server:
  port: ${PORT:${SERVER_PORT:0}}
---
spring:
  profiles: verb
words: ran,knew,had,saw,bought
server:
  port: ${PORT:${SERVER_PORT:0}}
---
spring:
  profiles: article
words: a,the
server:
  port: ${PORT:${SERVER_PORT:0}}
---
spring:
  profiles: adjective
words: reasonable,leaky,suspicious,ordinary,unlikely
server:
  port: ${PORT:${SERVER_PORT:0}}
---
spring:
  profiles: noun
words: boat,book,vote,seat,backpack,partition,groundhog  
server:
  port: ${PORT:${SERVER_PORT:0}}
---
spring:
  profiles: sentence
server:
  port: 8020
